services:
  container:
    image: ghcr.io/taoli-tools/taoli-tools-container:latest
    security_opt:
      - seccomp=/etc/docker/seccomp.json
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - data:/home/taoli/data
      - tailscale:/home/taoli/.local/share/tailscale/
      - /mnt:/home/taoli/cert
    networks:
      - public
      - private
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 0s
      update_config:
        order: stop-first
        parallelism: 1
        delay: 5s
      rollback_config:
        order: stop-first

  signer:
    image: ghcr.io/taoli-tools/taoli-tools-signer:latest
    security_opt:
      - seccomp=/etc/docker/seccomp.json
    secrets:
      - KEYCHAIN
      - CERT.pem
      - KEY.pem
    networks:
      - private
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 0s
      update_config:
        order: start-first
        parallelism: 1
        delay: 5s
      rollback_config:
        order: stop-first

networks:
  public:
    driver: overlay
    attachable: true
  private:
    driver: overlay
    attachable: true
    internal: true

volumes:
  data:
    driver: local
  tailscale:
    driver: local

secrets:
  KEYCHAIN:
    external: true
    name: taoli_tools_KEYCHAIN
  CERT.pem:
    external: true
    name: taoli_tools_CERT.pem
  KEY.pem:
    external: true
    name: taoli_tools_KEY.pem
